---
driver:
  name: docker
  hostname: etcd.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: etcd
  grains:
    noservices: True
  state_top:
    base:
      "*":
        - linux
        - etcd
  pillars:
    top.sls:
      base:
        "*":
          - debian_etcd_repo
          - etcd
  dependencies:
    - name: linux
      repo: git
      source: https://github.com/salt-formulas/salt-formula-linux.git
  pillars-from-files:
    debian_etcd_repo.sls: tests/pillar/repo_etcd.sls

verifier:
  name: inspec
  sudo: true

platforms:
  - name: <%=ENV['PLATFORM'] ||  'saltstack-ubuntu-xenial-salt-stable' %>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'epcim/salt:saltstack-ubuntu-xenial-salt-stable'%>
      platform: ubuntu

suites:

  - name: cluster
    provisioner:
      pillars-from-files:
        etcd.sls: tests/pillar/cluster.sls

  - name: proxy
    provisioner:
      pillars-from-files:
        etcd.sls: tests/pillar/proxy.sls

  - name: single
    provisioner:
      pillars-from-files:
        etcd.sls: tests/pillar/single.sls
# vim: ft=yaml sw=2 ts=2 sts=2 tw=125